apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: web-forum
data:
  APP_NAME: "Forum_Connect"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://ForumConnect.com"
  
  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "forum_app"
  DB_USERNAME: "forum_app_user"
  
  BROADCAST_DRIVER: "pusher"  
  PUSHER_APP_ID: "2072648"
  PUSHER_APP_KEY: "bd7b2266557abc0558cd"
  PUSHER_APP_SECRET: "02711b2fdbb383a6ae3e"
  PUSHER_HOST: "api-xxx.pusher.com"
  PUSHER_PORT: "443"
  PUSHER_SCHEME: "https"
  PUSHER_APP_CLUSTER: "ap1"  
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "public"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  
  MEMCACHED_HOST: "127.0.0.1"
  
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  
  MAIL_MAILER: "smtp"
  MAIL_HOST: "127.0.0.1"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Web Forum"