apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: web-forum
type: Opaque
stringData:
  APP_KEY: "base64:IkrZM7xND7v2yDQcF15VV20PypUO34IJPI57v6XUuiE="
  DB_PASSWORD: "password"
  MAIL_PASSWORD: ""
  PUSHER_APP_ID: "2072648"
  PUSHER_APP_KEY: "bd7b2266557abc0558cd"
  PUSHER_APP_SECRET: "02711b2fdbb383a6ae3e"