apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web-forum
type: Opaque
data:
  # echo -n 'password' | base64
  mysql-root-password: Unl1eHkyNyw=
  mysql-database: Zm9ydW1fYXBw
  mysql-username: cm9vdA==
  mysql-password: Unl1eHkyNyw=